// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PinoyPantry.API.Data;

#nullable disable

namespace PinoyPantry.API.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260313081024_Phase1_FixPriceColumnType")]
    partial class Phase1_FixPriceColumnType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PinoyPantry.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Noodles",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic Filipino instant noodles with savory sauce.",
                            ImageUrl = "",
                            Name = "Lucky Me Pancit Canton Original",
                            Price = 1.50m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 2,
                            Category = "Condiments",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Filipino cane vinegar, essential for dipping sauces.",
                            ImageUrl = "",
                            Name = "Datu Puti Sukang Maasim",
                            Price = 2.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 3,
                            Category = "Condiments",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "All-purpose Filipino soy sauce for cooking and dipping.",
                            ImageUrl = "",
                            Name = "Silver Swan Soy Sauce",
                            Price = 3.49m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 4,
                            Category = "Condiments",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sweet and tangy banana ketchup, a Filipino pantry staple.",
                            ImageUrl = "",
                            Name = "Jufran Banana Ketchup",
                            Price = 2.75m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 5,
                            Category = "Soups & Mixes",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tamarind soup base mix for the classic sinigang dish.",
                            ImageUrl = "",
                            Name = "Knorr Sinigang Mix",
                            Price = 1.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 6,
                            Category = "Condiments",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Filipino liver sauce perfect for lechon and grilled meats.",
                            ImageUrl = "",
                            Name = "Mang Tomas All-Around Sarsa",
                            Price = 3.25m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 7,
                            Category = "Canned Goods",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lower sodium canned pork, popular for Pinoy breakfast.",
                            ImageUrl = "",
                            Name = "Spam Lite",
                            Price = 4.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 8,
                            Category = "Canned Goods",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Canned tuna flakes in oil, great for pasta and rice dishes.",
                            ImageUrl = "",
                            Name = "Century Tuna Flakes in Oil",
                            Price = 2.50m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 9,
                            Category = "Snacks",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Light and crispy crackers, a classic Filipino snack.",
                            ImageUrl = "",
                            Name = "Skyflakes Crackers",
                            Price = 1.75m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 10,
                            Category = "Dairy",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full cream sterilized milk, long-life pantry staple.",
                            ImageUrl = "",
                            Name = "Bear Brand Sterilized Milk",
                            Price = 1.25m,
                            StockQuantity = 150
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
